### ISSUE TITLE
[Frage] Funktionen

### ISSUE THREAD

**Issue by budda85** [sWalbrun/bieterrunde#3]
Hi,
Ich hab euer Projekt über OpenOlitor gesehen.
Das sieht, wie schon bei OO geschrieben, super aus.

Wir haben bei uns in der Solawi mehrere Erzeuger und Anteile wie zum Beispiel: 
- Sommergemüse
- Wintergemüse
- Kartoffeln
- Honig
- ...

Hier gibt es auch noch unterschiedliche Kisten. Beim Sommergemüse z .B. große und kleine Anteile. 
Beim Honig ebenfalls und dazu kann man noch z. B. auf Kerzen und Wein bieten.

Kann ich das damit auch alles abbilden bei der Software oder kann ich pro Bieterrunde nur einen Anteil abfragen?

**Comment by sWalbrun** [comment]
Servus,

das wird derzeit nicht abgebildet. Wenn ich das richtig verstehe, dann wäre das einfach nur die Erweiterung um das Thema einer Bieterrunde und man würde dann pro "Kiste" eine eigene Bieterrunde durchführen bzw. eben mehrere parallel.

Alternativ köntne man darüber nachdenken, dass sich eine Bieterrunde aus mehreren Kisten zusammenstellt, die dann individuell pro Benutzer sind - aber das wäre technisch wohl eher aufwändig.

Wir können uns zu dem Thema aber gerne einfach mal austauschen, um erst mal genau das WAS bestimmen zu können, damit wir dann über ein WIE diskutieren können :-)

**Comment by budda85** [comment]
Also Sommergemüse und Wintergemüse in eine eigene Bieterrunde zu packen wäre ja kein Problem.
Wichtig wäre beim Sommergemüse, dass man innerhalb der Bieterrunde auf einen ganzen bzw. auf einen halben Anteil bieten kann.
Beide Anteile sind wichtig für Gesamte finanzierung. Zwei halbe Anteile wären ein ganzer. Deswegen sollte man hier unterscheiden können in der Bieterrunde.

**Comment by budda85** [comment]
Ich habe hier mal ein Beispiel, wie wir unsere Bieterrunde gemacht haben.
Dieses Jahr haben wir 9 Anteile, bei denen es teilweise auch andere Mengen gibt (klein und groß), wenn ich dafür jedesmal einen eigenen Link zur Verfügung stellen würde, könnte das zur Verwirrung sorgen. Zumal die kleinen und großen Anteile zusammen gehören. Zwei kleine Anteile sind bei uns dann ein großer und das muss ja mit in die Berrechnung.

https://umfrage.solawilue.de/index.php?r=survey/index&sid=269183&lang=de-informal

Vielleicht ist das mit dem Link jetzt ein wenig besser zu verstehen :-)

**Comment by sWalbrun** [comment]
Ja das hat geholfen. Das bringt auf jeden Fall eine neue Komplexität in die Sache rein, die so bisher noch nicht vorhanden ist.
Ich überlege mir mal eine architektonisches Konzept, mit dem man das Ganze abbilden kann und schaue wie aufwendig es werden würde. Ich melde mich wieder.

Beste Grüße

**Comment by sWalbrun** [comment]
Servus,

ich habe inzwischen Zeit gefunden große Teile der Features umzusetzen. Es wird in Zukunft möglich sein, dass eine Bieterrunde mit mehreren Themen angelegt werden kann und die Benutzer dann pro Thema ihre Gebote abgeben können. 
Für die Mitglieder wird das dann aktuell wie folgt aussehen:

![image](https://github.com/sWalbrun/bieterrunde/assets/38902857/b2dfa4ef-2a1b-4e19-bf93-4d9fa0286563)

Das heißt, dass jeder Benutzer über eine einzige Seite seine ganzen Gebote in einem Aufwasch abgeben kann. Das sollte auch genau dein Problem lösen wenn ich alles richtig verstanden habe.


Der Admin hat die Möglichkeit mehrere Themen anzulegen für eine Bieterrunde. Es wird dabei so sein, dass der Admin PRO Benutzer sagen kann, an welchen Themen sie beteiligt sind und mit welcher Anteilhöhe.

Es ist also möglich, dass Franz **einen** Anteil Eier bezieht und **zwei** Anteile Gemüse und Heike aber Eier und Honig bezieht.

![image](https://github.com/sWalbrun/bieterrunde/assets/38902857/3ac4422c-9746-47d7-802f-29e25d47bf4d)

![image](https://github.com/sWalbrun/bieterrunde/assets/38902857/0daac2df-cb93-43c6-b08d-67cb7f85306f)

Beste Grüße

**Comment by budda85** [comment]
Moin, das sieht super aus.
Eine extra zuordnung pro Person muss nicht unbedingt sein. Es kann sich bei jeder Bieterrunde jeder spontan entscheiden auf was er bieten möchte.
Letztes Jahr haben wir leider nicht alle Anteile vergeben können, da wurde dann auf Basis des Mittelwerts pro Korb entschieden, das wäre auch schön direkt zu sehen.

Nächste Woche würde ich das einmal installieren und testen.

Aber das gefällt mir echt gut.
Vielen Dank

**Comment by sWalbrun** [comment]
Servus,

Klar, gern.
Aktuell sieht das System vor, dass jeder sein Gebot abgeben muss, also eine "spontane" Zuordnung nicht möglich ist. 
Da kann man aber drüber nachdenken, dass Gebote grundsätzlich nicht zwingend erforderlich sind, sondern die Runde auch abgeschlossen werden kann wenn genügend Geld in Summe verfügbar sein wird.

Zur Installation: in der Readme steht drin was gemacht werden muss aber unterm Strich musst du nur das Script `serve.sh` ausführen und dann werden die dir ganzen Container hochgezogen und mit daten befüllt. Falls du Probleme dabei hast, dann lass es mich wissen. Es kann gut sein, dass sich noch Fehler darin befinden.

**Comment by sWalbrun** [comment]
Ah. Noch ne andere Info. Aktuell ist das solidarische Netz dabei eine VM bereitzustellen, um die Bieterrunde für alle solawis DE weit nutzbar zu machen, also auch potentiell für euch (wäre dann nur ein weiteres Mandat). Falls du Interesse hast, halte ich dich im Loop

**Comment by budda85** [comment]
Klar, sehr gerne.
